// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7zK7WbEvIaCM6YU_-8TsMXI1AJPA7p6o',
    appId: '1:558680818811:web:0a8a7dca39d64958c04ede',
    messagingSenderId: '558680818811',
    projectId: 'social-app-bf48b',
    authDomain: 'social-app-bf48b.firebaseapp.com',
    storageBucket: 'social-app-bf48b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp-c1-fy3lgFx5zcZbSDJ-gF8Pu5FB-Xs',
    appId: '1:558680818811:android:1a10bcaa46c0a9b0c04ede',
    messagingSenderId: '558680818811',
    projectId: 'social-app-bf48b',
    storageBucket: 'social-app-bf48b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPm4cuQ10WXEP2QEJWXQ67NSxNYTgxg28',
    appId: '1:558680818811:ios:be67c03f5f4b45afc04ede',
    messagingSenderId: '558680818811',
    projectId: 'social-app-bf48b',
    storageBucket: 'social-app-bf48b.appspot.com',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPm4cuQ10WXEP2QEJWXQ67NSxNYTgxg28',
    appId: '1:558680818811:ios:be67c03f5f4b45afc04ede',
    messagingSenderId: '558680818811',
    projectId: 'social-app-bf48b',
    storageBucket: 'social-app-bf48b.appspot.com',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7zK7WbEvIaCM6YU_-8TsMXI1AJPA7p6o',
    appId: '1:558680818811:web:ebce26add87b3a80c04ede',
    messagingSenderId: '558680818811',
    projectId: 'social-app-bf48b',
    authDomain: 'social-app-bf48b.firebaseapp.com',
    storageBucket: 'social-app-bf48b.appspot.com',
  );

}